apiVersion: v2
name: kusai-mastodon
description: ""
type: application
version: 0.1.2
appVersion: "0.5.0"
maintainers:
  - name: kasefuchs
    email: kasefuchs@protonmail.com
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
