{{- include "bjw-s.common.loader.init" . }}

{{- define "kasefuchs.kusai-mastodon.hardcodedValues" -}}
controllers:
  {{- range $controllerName, $controller := .Values.controllers }}
  {{ $controllerName }}:
    containers:
      main:
        image:
          tag: "{{ $.Chart.AppVersion }}"
  {{- end }}
{{- end -}}

{{- $_ := mergeOverwrite .Values (include "kasefuchs.kusai-mastodon.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}
